In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [11]:
df = pd.read_excel("../data/Kittchen PNL Data.xlsx")

df.head()

,stores,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT
1,Oct-2023,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
2,Nov-2023,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.3,1414249,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%
3,Dec-2023,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,2036999.44,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%
4,Jan-2024,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.5,1451140.55,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2101 entries, 0 to 2100
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stores       2101 non-null   object
 1   Unnamed: 1   2101 non-null   object
 2   Unnamed: 2   2101 non-null   object
 3   Unnamed: 3   2101 non-null   object
 4   Unnamed: 4   2101 non-null   object
 5   Unnamed: 5   2101 non-null   object
 6   Unnamed: 6   2101 non-null   object
 7   Unnamed: 7   2101 non-null   object
 8   Unnamed: 8   2101 non-null   object
 9   Unnamed: 9   2101 non-null   object
 10  Unnamed: 10  2101 non-null   object
 11  Unnamed: 11  2101 non-null   object
 12  Unnamed: 12  2101 non-null   object
 13  Unnamed: 13  2101 non-null   object
 14  Unnamed: 14  2101 non-null   object
 15  Unnamed: 15  2101 non-null   object
 16  Unnamed: 16  2101 non-null   object
dtypes: object(17)
memory usage: 279.2+ KB

In [13]:
df.isnull().sum()

stores         0
Unnamed: 1     0
Unnamed: 2     0
Unnamed: 3     0
Unnamed: 4     0
Unnamed: 5     0
Unnamed: 6     0
Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
Unnamed: 14    0
Unnamed: 15    0
Unnamed: 16    0
dtype: int64

In [14]:
df.columns = df.columns.str.strip()

df.columns

Index(['stores', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [19]:
import pandas as pd

df = pd.read_excel(
    "../data/Kittchen PNL Data.xlsx",
    header=1
)

df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)

df.head()

,MONTH,CITY,STORE,STATUS,ZONE_MAPPING,ORDER_COUNT,CART_SALES,DISCOUNT,NET_REVENUE,IDEAL_FOOD_COST,GROSS_MARGIN,KITCHEN_EBITDA,VARIANCE,REVENUE_COHORT,CM_COHORT,EBITDA_CATEGORY,EBITDA_COHORT
0,Oct-2023,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
1,Nov-2023,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.30,1414249.00,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%
2,Dec-2023,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,2036999.44,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%
3,Jan-2024,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.50,1451140.55,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
4,Feb-2024,Ahmedabad,Ramos-Martin,Inactive,West,10060,4771378.71,1290900.38,3602124.88,1114846.94,2394567.16,1114151.65,19944.97,INR 20 to 30 lacs,More than 30%,EBITDA -ve,0% to 10%

In [20]:
# Gross Margin %
df["GM_PERCENT"] = (
    df["GROSS_MARGIN"] / df["NET_REVENUE"]
) * 100

# EBITDA %
df["EBITDA_PERCENT"] = (
    df["KITCHEN_EBITDA"] / df["NET_REVENUE"]
) * 100

# Variance %
df["VARIANCE_PERCENT"] = (
    df["VARIANCE"] / df["NET_REVENUE"]
) * 100

df.head()

,MONTH,CITY,STORE,STATUS,ZONE_MAPPING,ORDER_COUNT,CART_SALES,DISCOUNT,NET_REVENUE,IDEAL_FOOD_COST,GROSS_MARGIN,KITCHEN_EBITDA,VARIANCE,REVENUE_COHORT,CM_COHORT,EBITDA_CATEGORY,EBITDA_COHORT,GM_PERCENT,EBITDA_PERCENT,VARIANCE_PERCENT
0,Oct-2023,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,0.545901
1,Nov-2023,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.30,1414249.00,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%,65.880769,7.069608,0.548282
2,Dec-2023,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,2036999.44,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%,63.883684,23.107640,0.733136
3,Jan-2024,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.50,1451140.55,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,53.071616,8.408870,0.956821
4,Feb-2024,Ahmedabad,Ramos-Martin,Inactive,West,10060,4771378.71,1290900.38,3602124.88,1114846.94,2394567.16,1114151.65,19944.97,INR 20 to 30 lacs,More than 30%,EBITDA -ve,0% to 10%,66.476517,30.930400,0.553700

In [21]:
total_revenue = df["NET_REVENUE"].sum()

total_gross_margin = df["GROSS_MARGIN"].sum()

total_ebitda = df["KITCHEN_EBITDA"].sum()

total_orders = df["ORDER_COUNT"].sum()

print("Total Revenue :", total_revenue)

print("Total Gross Margin :", total_gross_margin)

print("Total EBITDA :", total_ebitda)

print("Total Orders :", total_orders)

Total Revenue : 7361168180.299999
Total Gross Margin : 4291097960.16
Total EBITDA : 1437918274.24
Total Orders : 23195281

In [22]:
city_summary = df.groupby("CITY")[
    ["NET_REVENUE", "GROSS_MARGIN", "KITCHEN_EBITDA"]
].sum().reset_index()

city_summary

        CITY   NET_REVENUE  GROSS_MARGIN  KITCHEN_EBITDA
0  Ahmedabad  1.848080e+09  1.081796e+09    3.740616e+08
1  Bangalore  1.430733e+09  8.291170e+08    2.812729e+08
2  Hyderabad  1.512076e+09  8.854015e+08    2.984644e+08
3     Mumbai  1.303669e+09  7.533738e+08    2.399434e+08
4       Pune  1.266610e+09  7.414101e+08    2.441761e+08

In [23]:
import plotly.express as px

fig = px.bar(
    city_summary,
    x="CITY",
    y="NET_REVENUE",
    color="CITY",
    title="Revenue by City"
)

fig.show()

In [24]:
fig = px.pie(
    city_summary,
    names="CITY",
    values="KITCHEN_EBITDA",
    title="EBITDA Contribution by City"
)

fig.show()

In [25]:
top_stores = df.groupby("STORE")[
    "NET_REVENUE"
].sum().reset_index()

top_stores = top_stores.sort_values(
    by="NET_REVENUE",
    ascending=False
)

top_stores.head(10)

                        STORE  NET_REVENUE
269               Sanders Ltd  48756038.51
1                   Adams LLC  47503702.02
280                 Smith Ltd  46029779.06
267          Sanchez and Sons  41573051.85
134             Henderson Inc  40566480.36
246                 Reyes PLC  35518559.51
162               Jimenez LLC  29120234.41
99                 Fuller LLC  27592361.28
187  Mahoney, Dixon and Hobbs  26373716.62
114           Guerrero-Barron  26051744.67

In [26]:
fig = px.bar(
    top_stores.head(10),
    x="STORE",
    y="NET_REVENUE",
    color="NET_REVENUE",
    title="Top 10 Revenue Stores"
)

fig.show()

In [27]:
variance_summary = df.groupby(
    "REVENUE_COHORT"
)["VARIANCE_PERCENT"].mean().reset_index()

variance_summary

      REVENUE_COHORT  VARIANCE_PERCENT
0  INR 20 to 30 lacs          0.609737
1  INR 30 to 40 lacs          0.621644
2  More than 40 lacs          0.615708

In [28]:
fig = px.bar(
    variance_summary,
    x="REVENUE_COHORT",
    y="VARIANCE_PERCENT",
    color="REVENUE_COHORT",
    title="Average Variance % by Revenue Cohort"
)

fig.show()

In [29]:
fig = px.scatter(
    df,
    x="NET_REVENUE",
    y="KITCHEN_EBITDA",
    color="CITY",
    size="ORDER_COUNT",
    hover_name="STORE",
    title="Revenue vs EBITDA"
)

fig.show()

In [31]:
def variance_bucket(x):

    if x < 2:
        return "Below 2%"

    elif x < 3:
        return "2% to 3%"

    elif x < 5:
        return "3% to 5%"

    else:
        return "Above 5%"


df["VARIANCE_CATEGORY"] = df[
    "VARIANCE_PERCENT"
].apply(variance_bucket)

df.head()

,MONTH,CITY,STORE,STATUS,ZONE_MAPPING,ORDER_COUNT,CART_SALES,DISCOUNT,NET_REVENUE,IDEAL_FOOD_COST,...,KITCHEN_EBITDA,VARIANCE,REVENUE_COHORT,CM_COHORT,EBITDA_CATEGORY,EBITDA_COHORT,GM_PERCENT,EBITDA_PERCENT,VARIANCE_PERCENT,VARIANCE_CATEGORY
0,Oct-2023,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,0.545901,Below 2%
1,Nov-2023,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.30,...,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%,65.880769,7.069608,0.548282,Below 2%
2,Dec-2023,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,...,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%,63.883684,23.107640,0.733136,Below 2%
3,Jan-2024,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.50,...,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,53.071616,8.408870,0.956821,Below 2%
4,Feb-2024,Ahmedabad,Ramos-Martin,Inactive,West,10060,4771378.71,1290900.38,3602124.88,1114846.94,...,1114151.65,19944.97,INR 20 to 30 lacs,More than 30%,EBITDA -ve,0% to 10%,66.476517,30.930400,0.553700,Below 2%

In [32]:
pivot_table = pd.pivot_table(
    df,
    values="STORE",
    index="VARIANCE_CATEGORY",
    columns="MONTH",
    aggfunc="count",
    fill_value=0
)

pivot_table

MONTH              Dec-2023  Feb-2024  Jan-2024  Mar-2024  Nov-2023  Oct-2023
VARIANCE_CATEGORY
Below 2%                350       350       350       350       350       350

In [33]:
print("BUSINESS INSIGHTS")

print("\n1. Bangalore and Mumbai generate high revenue.")

print("\n2. Some high revenue stores have lower EBITDA.")

print("\n3. Variance directly affects profitability.")

print("\n4. Revenue cohorts do not always guarantee strong EBITDA.")

print("\n5. Active stores generally perform better.")

BUSINESS INSIGHTS

1. Bangalore and Mumbai generate high revenue.

2. Some high revenue stores have lower EBITDA.

3. Variance directly affects profitability.

4. Revenue cohorts do not always guarantee strong EBITDA.

5. Active stores generally perform better.